### ISSUE TITLE
State Management  -CRUD 

### ISSUE THREAD

**Issue by CppoCompany** [CppoCompany/CppoApp#2]
**Purpose of the task:**
Create a state manager infrastructure without ngrx that will be able to create, delete and update.

- [ ]  #2 State Management Create Crud without Ngrx -action reducer selector 
- [ ]  #2 State Management Create Crud without Ngrx -Research another State 
- [ ]  #2 State Management Create Crud without Ngrx-Write an explanation of how to work with the state
