### ISSUE TITLE
Research Standalone Component with Lazy Loading 

### ISSUE THREAD

**Issue by CppoCompany** [CppoCompany/CppoApp#3]
**Research Standalone Component with Lazy Loading** 
The goal in this task is to explore how to go with a standalone component with lazy loading

- [ ]  #3 Research Standalone Component with Lazy Loading - Investigate how to work if  standalone Component
- [ ]  #3  Research Standalone Component with Lazy Loading - Create a component that produces a standalone component with the creation of lazy loading.
- [ ]  #3 Research Standalone Component with Lazy Loading - write docs of standalone Component
